In [1]:
import pandas as pd

In [3]:
disruptions = pd.read_csv("../data/raw/bodsdatacatalogue/disruptions_data_catalogue.csv")

In [4]:
disruptions.shape

(336, 12)

In [5]:
disruptions.columns.to_list()

['Organisation',
 'ID',
 'Validity start',
 'Validity end',
 'Publication start',
 'Publication end',
 'Reason',
 'Planned',
 'Modes affected',
 'Operators affected',
 'Services affected',
 'Stops affected']

In [6]:
disruptions.head()

,Organisation,ID,Validity start,Validity end,Publication start,Publication end,Reason,Planned,Modes affected,Operators affected,Services affected,Stops affected
0,West of England,18224249-29cf-4f65-a023-11067e7c2b6f,Sun Sep 01 2024 08:00:00 GMT+0000 (Coordinated...,NaN,Sun Sep 01 2024 08:00:00 GMT+0000 (Coordinated...,NaN,roadworks,True,bus,NaN,NaN,NaN
1,WYCA,2b9e1d8f-b0ee-43a7-8ca5-7334d6fc4587,Mon Nov 04 2024 08:30:00 GMT+0000 (Coordinated...,NaN,Mon Nov 04 2024 08:30:00 GMT+0000 (Coordinated...,NaN,roadworks,True,bus,NaN,1.0,4.0
2,West of England,ba174836-2698-4f06-8f22-e6c90aca9a7d,Thu Mar 06 2025 09:16:00 GMT+0000 (Coordinated...,NaN,Thu Mar 06 2025 09:16:00 GMT+0000 (Coordinated...,NaN,roadworks,False,bus,NaN,1.0,1.0
3,West of England,8e8d2259-4d28-490b-9785-c08b0fd034bd,Sun Mar 30 2025 22:01:00 GMT+0000 (Coordinated...,NaN,Sun Mar 30 2025 00:01:00 GMT+0000 (Coordinated...,NaN,roadworks,True,bus,NaN,15.0,1.0
4,West of England,526571b9-9ead-4d5a-a7f0-511c879be31e,Sun Apr 06 2025 22:00:00 GMT+0000 (Coordinated...,Sun Nov 01 2026 23:59:00 GMT+0000 (Coordinated...,Mon Mar 31 2025 10:39:00 GMT+0000 (Coordinated...,Sun Nov 01 2026 23:59:00 GMT+0000 (Coordinated...,repairWork,True,bus,NaN,1.0,1.0

In [10]:
wyca_disruptions = disruptions[disruptions['Organisation'].str.contains('WYCA|West Yorkshire', case=False, na=False)]

In [11]:
wyca_disruptions.shape

(60, 12)

In [12]:
wyca_disruptions.head()

,Organisation,ID,Validity start,Validity end,Publication start,Publication end,Reason,Planned,Modes affected,Operators affected,Services affected,Stops affected
1,WYCA,2b9e1d8f-b0ee-43a7-8ca5-7334d6fc4587,Mon Nov 04 2024 08:30:00 GMT+0000 (Coordinated...,NaN,Mon Nov 04 2024 08:30:00 GMT+0000 (Coordinated...,NaN,roadworks,True,bus,NaN,1.0,4.0
9,WYCA,de178bce-11a5-4a61-9897-5360b40c0e37,Sat Aug 23 2025 11:34:00 GMT+0000 (Coordinated...,Mon Aug 31 2026 22:59:00 GMT+0000 (Coordinated...,Sat Aug 23 2025 11:34:00 GMT+0000 (Coordinated...,Mon Aug 31 2026 22:59:00 GMT+0000 (Coordinated...,roadClosed,True,bus,NaN,9.0,NaN
12,WYCA,289217e6-6830-4718-97f9-59621a5064f2,Mon Nov 24 2025 06:00:00 GMT+0000 (Coordinated...,Sun Nov 07 2027 23:59:00 GMT+0000 (Coordinated...,Sat Nov 22 2025 09:00:00 GMT+0000 (Coordinated...,Sun Nov 07 2027 23:59:00 GMT+0000 (Coordinated...,roadworks,True,bus,NaN,8.0,3.0
13,WYCA,f258b9b9-0c10-4e73-b4f9-830781431919,Wed Nov 26 2025 10:29:00 GMT+0000 (Coordinated...,NaN,Wed Nov 26 2025 10:29:00 GMT+0000 (Coordinated...,NaN,roadworks,True,bus,NaN,1.0,1.0
19,WYCA,630d9779-55de-4b37-9a2c-fe0c70285bb1,Fri Jan 16 2026 10:59:00 GMT+0000 (Coordinated...,NaN,Fri Jan 16 2026 10:59:00 GMT+0000 (Coordinated...,NaN,roadworks,True,bus,NaN,11.0,1.0

In [14]:
wyca_disruptions.isna().sum()

Organisation           0
ID                     0
Validity start         0
Validity end          16
Publication start      0
Publication end       16
Reason                 0
Planned                0
Modes affected         0
Operators affected    60
Services affected      0
Stops affected         4
dtype: int64

## 2. Timetables Data Exploration (Parsed from XML)

In [16]:
import pandas as pd
df = pd.read_csv("../data/interim/timetables_parsed.csv")
print(df.shape)
print(df.isna().sum())
print(df['days_of_week'].value_counts().head(10))
df.head()

(68337, 11)
source_file               0
operator_name             0
national_operator_code    0
service_code              0
line_name                 0
origin                    0
destination               0
days_of_week              0
operating_start_date      0
journey_code              0
departure_time            0
dtype: int64
days_of_week
Monday,Tuesday,Wednesday,Thursday,Friday                    25807
Saturday                                                    24473
Sunday                                                      12735
Friday                                                       2579
Monday,Tuesday,Wednesday,Thursday                            2542
Tuesday,Wednesday,Thursday,Friday                              68
Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday       53
Monday,Tuesday,Thursday,Friday                                 30
Wednesday                                                      29
Thursday                                                       10
Name: count, dtype: int64

/tmp/ipykernel_36865/4206838823.py:2: DtypeWarning: Columns (0: journey_code) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/interim/timetables_parsed.csv")

,source_file,operator_name,national_operator_code,service_code,line_name,origin,destination,days_of_week,operating_start_date,journey_code,departure_time
0,203-None--SYRK-BY-2026-04-12-BY_12th_April_202...,Stagecoach,SYRK,PB0000092:372,203,Doncaster,Wombwell,"Monday,Tuesday,Wednesday,Thursday,Friday",2026-05-30,1502,07:24:00
1,203-None--SYRK-BY-2026-04-12-BY_12th_April_202...,Stagecoach,SYRK,PB0000092:372,203,Doncaster,Wombwell,"Monday,Tuesday,Wednesday,Thursday,Friday",2026-05-30,1501,08:15:00
2,203-None--SYRK-BY-2026-04-12-BY_12th_April_202...,Stagecoach,SYRK,PB0000092:372,203,Doncaster,Wombwell,"Monday,Tuesday,Wednesday,Thursday,Friday",2026-05-30,1504,09:22:00
3,203-None--SYRK-BY-2026-04-12-BY_12th_April_202...,Stagecoach,SYRK,PB0000092:372,203,Doncaster,Wombwell,"Monday,Tuesday,Wednesday,Thursday,Friday",2026-05-30,1503,10:35:00
4,203-None--SYRK-BY-2026-04-12-BY_12th_April_202...,Stagecoach,SYRK,PB0000092:372,203,Doncaster,Wombwell,"Monday,Tuesday,Wednesday,Thursday,Friday",2026-05-30,1506,12:08:00

In [17]:
wy_places = ['Leeds', 'Bradford', 'Wakefield', 'Huddersfield', 'Halifax', 
             'Dewsbury', 'Kirklees', 'Calderdale', 'Batley', 'Pudsey', 
             'Keighley', 'Brighouse', 'Castleford', 'Pontefract', 'Selby']

# quick check: how many rows have origin/destination matching known WY places
in_scope = df[df['origin'].str.contains('|'.join(wy_places), case=False, na=False) |
              df['destination'].str.contains('|'.join(wy_places), case=False, na=False)]

print(f"In-scope (West Yorkshire) rows: {in_scope.shape[0]} of {df.shape[0]}")
print(df['origin'].value_counts().head(20))

In-scope (West Yorkshire) rows: 34628 of 68337
origin
Barnsley                    6194
Leeds                       3741
Wakefield                   3204
Chesterfield                3114
Bradford                    3053
Keighley                    1869
White Rose/Middleton        1774
Huddersfield                1771
Middleton, Thorpe Lane      1770
Harrogate                   1737
Rotherham                   1701
Woodhouse                   1562
Leeds Bus Station           1458
Victoria D                  1433
Halifax                     1418
Leeds City Bus Station      1230
Bramley                     1202
Whinmoor Shopping Centre    1188
Blackburn                   1177
HALIFAX BUS STATION         1168
Name: count, dtype: int64

In [18]:
# Known out-of-scope areas identified from the data (bordering counties, not West Yorkshire)
out_of_scope = ['Barnsley', 'Chesterfield', 'Rotherham', 'Harrogate', 'Blackburn', 
                 'Sheffield', 'Doncaster', 'Wombwell', 'Derby', 'Preston', 'Burnley']

# Known in-scope West Yorkshire boroughs/towns (Leeds, Bradford, Wakefield, Kirklees, Calderdale)
wy_places = ['Leeds', 'Bradford', 'Wakefield', 'Huddersfield', 'Halifax', 
             'Dewsbury', 'Batley', 'Pudsey', 'Keighley', 'Brighouse', 
             'Castleford', 'Pontefract', 'Bramley', 'Morley', 'Otley',
             'Ilkley', 'Shipley', 'Cleckheaton', 'Mirfield', 'Ossett']

# Exclude rows where EITHER origin or destination is clearly out of scope
mask_out = (df['origin'].str.contains('|'.join(out_of_scope), case=False, na=False) |
            df['destination'].str.contains('|'.join(out_of_scope), case=False, na=False))

# Keep rows where EITHER origin or destination matches a known WY place
mask_in = (df['origin'].str.contains('|'.join(wy_places), case=False, na=False) |
           df['destination'].str.contains('|'.join(wy_places), case=False, na=False))

df_wy = df[mask_in & ~mask_out].copy()

print(f"Filtered West Yorkshire rows: {df_wy.shape[0]} of {df.shape[0]}")
print(df_wy['origin'].value_counts().head(15))
print(df_wy['operator_name'].value_counts())

Filtered West Yorkshire rows: 34703 of 68337
origin
Leeds                             3741
Wakefield                         3204
Bradford                          2947
Keighley                          1869
Huddersfield                      1771
Leeds Bus Station                 1458
Halifax                           1418
Leeds City Bus Station            1230
Bramley                           1202
Whinmoor Shopping Centre          1188
HALIFAX BUS STATION               1168
Bradford Interchange              1100
Halifax Bus Station                902
Leeds Bus Station/Liberty Dock     847
Pontefract                         710
Name: count, dtype: int64
operator_name
Arriva Yorkshire             9911
First Leeds                  9282
First Bradford               6126
FIRST WEST YORKSHIRE LTD     3826
The Keighley Bus Company     1940
Team Pennine                 1441
Go Ahead West Yorkshire       775
The Harrogate Bus Company     688
Coastliner                    442
Flyer                         272
Name: count, dtype: int64

# Finding 1: Stagecoach has vanished entirely from the filtered list

**Despite being listed under the West Yorkshire geographic filter on BODS, the Stagecoach Yorkshire dataset was found to predominantly serve South Yorkshire routes (Barnsley, Doncaster, Rotherham) and was consequently excluded after geographic validation.**

# Finding 2: Transdev's brand names explain the operator list

**Transdev Blazefield doesn't operate under its own name on the ground — it runs regional sub-brands: The Keighley Bus Company, Team Pennine, The Harrogate Bus Company, Coastliner, Flyer.**

In [19]:
df_wy.to_csv("../data/interim/timetables_west_yorkshire.csv", index=False)

**Now: 3-month date expansion:**

In [20]:
wyca_disruptions['Validity start'] = pd.to_datetime(wyca_disruptions['Validity start'], errors='coerce', utc=True)
wyca_disruptions['Validity end'] = pd.to_datetime(wyca_disruptions['Validity end'], errors='coerce', utc=True)

window_start = pd.Timestamp("2026-04-01", tz="UTC")
window_end = pd.Timestamp("2026-06-30", tz="UTC")

scoped_disruptions = wyca_disruptions[
    (wyca_disruptions['Validity start'] <= window_end) &
    ((wyca_disruptions['Validity end'].isna()) | (wyca_disruptions['Validity end'] >= window_start))
].copy()

print(scoped_disruptions.shape)
scoped_disruptions.head(10)

(0, 12)

/tmp/ipykernel_36865/685546871.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  wyca_disruptions['Validity start'] = pd.to_datetime(wyca_disruptions['Validity start'], errors='coerce', utc=True)
/tmp/ipykernel_36865/685546871.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  wyca_disruptions['Validity end'] = pd.to_datetime(wyca_disruptions['Validity end'], errors='coerce', utc=True)

Empty DataFrame
Columns: [Organisation, ID, Validity start, Validity end, Publication start, Publication end, Reason, Planned, Modes affected, Operators affected, Services affected, Stops affected]
Index: []

In [21]:
print(wyca_disruptions['Validity start'].dtype)
print(wyca_disruptions['Validity start'].isna().sum())
print(wyca_disruptions['Validity start'].head(10))

datetime64[s, UTC]
60
1    NaT
9    NaT
12   NaT
13   NaT
19   NaT
22   NaT
23   NaT
31   NaT
40   NaT
41   NaT
Name: Validity start, dtype: datetime64[s, UTC]

In [22]:
import re

# Reload untouched from the CSV filter (avoid double-parsing an already-corrupted column)
raw_disruptions = disruptions[disruptions['Organisation'].str.contains('WYCA|West Yorkshire', case=False, na=False)].copy()

def clean_and_parse_date(series):
    # Strip the trailing "(Coordinated Universal Time)" style text, keep the GMT offset
    cleaned = series.astype(str).str.replace(r'\s*\(.*\)$', '', regex=True)
    return pd.to_datetime(cleaned, errors='coerce', utc=True)

raw_disruptions['Validity start'] = clean_and_parse_date(raw_disruptions['Validity start'])
raw_disruptions['Validity end'] = clean_and_parse_date(raw_disruptions['Validity end'])

print("Parsed successfully:", raw_disruptions['Validity start'].notna().sum(), "of", len(raw_disruptions))
print(raw_disruptions['Validity start'].head(10))

Parsed successfully: 60 of 60
1    2024-11-04 08:30:00+00:00
9    2025-08-23 11:34:00+00:00
12   2025-11-24 06:00:00+00:00
13   2025-11-26 10:29:00+00:00
19   2026-01-16 10:59:00+00:00
22   2026-01-27 13:07:00+00:00
23   2026-01-28 09:39:00+00:00
31   2026-03-02 06:00:00+00:00
40   2026-04-02 12:08:00+00:00
41   2026-04-07 05:00:00+00:00
Name: Validity start, dtype: datetime64[us, UTC]

In [23]:
print(wyca_disruptions['Validity start'].dtype)
print(wyca_disruptions['Validity start'].isna().sum())
print(wyca_disruptions['Validity start'].head(10))

datetime64[s, UTC]
60
1    NaT
9    NaT
12   NaT
13   NaT
19   NaT
22   NaT
23   NaT
31   NaT
40   NaT
41   NaT
Name: Validity start, dtype: datetime64[s, UTC]

In [27]:
window_start = pd.Timestamp("2026-04-01", tz="UTC")
window_end = pd.Timestamp("2026-06-30", tz="UTC")

scoped_disruptions = raw_disruptions[
    (raw_disruptions['Validity start'] <= window_end) &
    ((raw_disruptions['Validity end'].isna()) | (raw_disruptions['Validity end'] >= window_start))
].copy()

print(scoped_disruptions.shape)
scoped_disruptions[['ID', 'Validity start', 'Validity end', 'Reason', 'Planned', 'Services affected']]

(24, 12)

,ID,Validity start,Validity end,Reason,Planned,Services affected
1,2b9e1d8f-b0ee-43a7-8ca5-7334d6fc4587,2024-11-04 08:30:00+00:00,NaT,roadworks,True,1.0
9,de178bce-11a5-4a61-9897-5360b40c0e37,2025-08-23 11:34:00+00:00,2026-08-31 22:59:00+00:00,roadClosed,True,9.0
12,289217e6-6830-4718-97f9-59621a5064f2,2025-11-24 06:00:00+00:00,2027-11-07 23:59:00+00:00,roadworks,True,8.0
13,f258b9b9-0c10-4e73-b4f9-830781431919,2025-11-26 10:29:00+00:00,NaT,roadworks,True,1.0
19,630d9779-55de-4b37-9a2c-fe0c70285bb1,2026-01-16 10:59:00+00:00,NaT,roadworks,True,11.0
22,706b6b5f-532e-4e92-ba5b-80418e2c5807,2026-01-27 13:07:00+00:00,2026-07-31 22:59:00+00:00,roadClosed,True,1.0
23,7b4e17d3-95c1-46aa-99c0-08ff6e350bfd,2026-01-28 09:39:00+00:00,NaT,roadworks,True,12.0
31,f9b01a78-5ff0-4e37-a4a7-2b2d65a98261,2026-03-02 06:00:00+00:00,2026-12-04 23:59:00+00:00,routeDiversion,True,1.0
40,43864a74-527d-494b-941a-dc2c99b2210e,2026-04-02 12:08:00+00:00,2026-11-01 23:59:00+00:00,roadworks,False,1.0
41,fce0f123-f591-46ef-9242-d970c24d1b85,2026-04-07 05:00:00+00:00,2027-01-15 23:59:00+00:00,roadworks,True,2.0
48,161e4b52-cc54-488d-bf72-a999d5743421,2026-04-21 05:00:00+00:00,2026-09-04 22:59:00+00:00,roadworks,True,5.0
49,16bc4ee7-8f4b-4da4-9a8e-c9450e3cc9ec,2026-04-22 11:34:00+00:00,2026-09-18 22:59:00+00:00,routeDiversion,True,4.0
50,66b28bdf-d018-4ee5-b837-587fcccec5cc,2026-04-28 03:00:00+00:00,NaT,roadworks,True,4.0
51,0bda7948-bd66-4945-b1cc-00220bf69040,2026-04-30 13:13:00+00:00,NaT,vandalism,True,1.0
55,abdfb8c1-7f5e-4396-9140-d427070bda64,2026-05-13 08:20:00+00:00,NaT,roadworks,True,1.0
56,9f0ba969-9631-4311-9956-a06ff6a41673,2026-05-15 08:53:00+00:00,NaT,roadworks,False,3.0
62,c45f870c-2272-403b-9d9c-9d3eab5debda,2026-05-21 05:00:00+00:00,2026-11-27 23:59:00+00:00,roadworks,True,3.0
64,aeeab4e6-ae1e-4dec-ae8c-f5136bcc62dd,2026-05-21 06:47:00+00:00,NaT,roadworks,False,2.0
73,3ea82274-0db3-441a-a725-1a41e238be59,2026-06-02 08:49:00+00:00,NaT,roadworks,False,1.0
75,b1fc65da-5ac6-4d75-9604-5f40c88d7b51,2026-06-08 05:00:00+00:00,2026-07-17 22:59:00+00:00,roadworks,True,2.0
77,7f89b42c-8814-4873-8232-5e39c0642d96,2026-06-08 09:37:00+00:00,NaT,roadworks,True,1.0
82,5a57b8f5-222e-4e54-951e-fe0508019f9a,2026-06-14 08:01:00+00:00,NaT,roadworks,False,1.0
84,b7921958-134b-48e9-9913-4ed5ad3e50ce,2026-06-15 19:00:00+00:00,2026-07-18 05:00:00+00:00,roadworks,True,2.0
90,d67e5b21-f0dc-4143-a6a4-de4ddf9090c7,2026-06-23 10:45:00+00:00,NaT,roadworks,True,6.0

In [28]:
# persist the scoped WYCA disruptions so downstream notebooks don't need to redo this filtering
scoped_disruptions.to_csv("../data/interim/wyca_disruptions_scoped.csv", index=False)
print("Saved.")

Saved.