In [1]:
import pandas as pd

In [3]:
disruptions = pd.read_csv("../data/raw/bodsdatacatalogue/disruptions_data_catalogue.csv")

In [4]:
disruptions.shape

(336, 12)

In [5]:
disruptions.columns.to_list()

['Organisation',
 'ID',
 'Validity start',
 'Validity end',
 'Publication start',
 'Publication end',
 'Reason',
 'Planned',
 'Modes affected',
 'Operators affected',
 'Services affected',
 'Stops affected']

In [6]:
disruptions.head()

,Organisation,ID,Validity start,Validity end,Publication start,Publication end,Reason,Planned,Modes affected,Operators affected,Services affected,Stops affected
0,West of England,18224249-29cf-4f65-a023-11067e7c2b6f,Sun Sep 01 2024 08:00:00 GMT+0000 (Coordinated...,NaN,Sun Sep 01 2024 08:00:00 GMT+0000 (Coordinated...,NaN,roadworks,True,bus,NaN,NaN,NaN
1,WYCA,2b9e1d8f-b0ee-43a7-8ca5-7334d6fc4587,Mon Nov 04 2024 08:30:00 GMT+0000 (Coordinated...,NaN,Mon Nov 04 2024 08:30:00 GMT+0000 (Coordinated...,NaN,roadworks,True,bus,NaN,1.0,4.0
2,West of England,ba174836-2698-4f06-8f22-e6c90aca9a7d,Thu Mar 06 2025 09:16:00 GMT+0000 (Coordinated...,NaN,Thu Mar 06 2025 09:16:00 GMT+0000 (Coordinated...,NaN,roadworks,False,bus,NaN,1.0,1.0
3,West of England,8e8d2259-4d28-490b-9785-c08b0fd034bd,Sun Mar 30 2025 22:01:00 GMT+0000 (Coordinated...,NaN,Sun Mar 30 2025 00:01:00 GMT+0000 (Coordinated...,NaN,roadworks,True,bus,NaN,15.0,1.0
4,West of England,526571b9-9ead-4d5a-a7f0-511c879be31e,Sun Apr 06 2025 22:00:00 GMT+0000 (Coordinated...,Sun Nov 01 2026 23:59:00 GMT+0000 (Coordinated...,Mon Mar 31 2025 10:39:00 GMT+0000 (Coordinated...,Sun Nov 01 2026 23:59:00 GMT+0000 (Coordinated...,repairWork,True,bus,NaN,1.0,1.0

In [10]:
wyca_disruptions = disruptions[disruptions['Organisation'].str.contains('WYCA|West Yorkshire', case=False, na=False)]

In [11]:
wyca_disruptions.shape

(60, 12)

In [12]:
wyca_disruptions.head()

,Organisation,ID,Validity start,Validity end,Publication start,Publication end,Reason,Planned,Modes affected,Operators affected,Services affected,Stops affected
1,WYCA,2b9e1d8f-b0ee-43a7-8ca5-7334d6fc4587,Mon Nov 04 2024 08:30:00 GMT+0000 (Coordinated...,NaN,Mon Nov 04 2024 08:30:00 GMT+0000 (Coordinated...,NaN,roadworks,True,bus,NaN,1.0,4.0
9,WYCA,de178bce-11a5-4a61-9897-5360b40c0e37,Sat Aug 23 2025 11:34:00 GMT+0000 (Coordinated...,Mon Aug 31 2026 22:59:00 GMT+0000 (Coordinated...,Sat Aug 23 2025 11:34:00 GMT+0000 (Coordinated...,Mon Aug 31 2026 22:59:00 GMT+0000 (Coordinated...,roadClosed,True,bus,NaN,9.0,NaN
12,WYCA,289217e6-6830-4718-97f9-59621a5064f2,Mon Nov 24 2025 06:00:00 GMT+0000 (Coordinated...,Sun Nov 07 2027 23:59:00 GMT+0000 (Coordinated...,Sat Nov 22 2025 09:00:00 GMT+0000 (Coordinated...,Sun Nov 07 2027 23:59:00 GMT+0000 (Coordinated...,roadworks,True,bus,NaN,8.0,3.0
13,WYCA,f258b9b9-0c10-4e73-b4f9-830781431919,Wed Nov 26 2025 10:29:00 GMT+0000 (Coordinated...,NaN,Wed Nov 26 2025 10:29:00 GMT+0000 (Coordinated...,NaN,roadworks,True,bus,NaN,1.0,1.0
19,WYCA,630d9779-55de-4b37-9a2c-fe0c70285bb1,Fri Jan 16 2026 10:59:00 GMT+0000 (Coordinated...,NaN,Fri Jan 16 2026 10:59:00 GMT+0000 (Coordinated...,NaN,roadworks,True,bus,NaN,11.0,1.0